{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-groene-salade-sla-mix-komkommer-tomaat-340-g/70714", "naam": "1 de Beste Groene salade sla mix komkommer & tomaat", "inhoud": "340 g", "prijs": "2.99", "omschrijving": "Salade met tomaat, komkommer, gekookt ei en honing-mosterddressing", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-zalm-450-g/71065", "naam": "1 de Beste Maaltijdsalade zalm", "inhoud": "450 g", "prijs": "4.69", "omschrijving": "Maaltijdsalade met gekookte pasta, dille-mieriksworteldressing, gerookte zalm en kappertjes", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/fresh-easy-pastasalade-pesto-350-g/69139", "naam": "Fresh & easy Pastasalade pesto", "inhoud": "350 g", "prijs": "3.49", "omschrijving": "Pastasalade met pesto, pijnboompitten en kaas.", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/fresh-easy-lunchsalade-witte-kaas-hummus-400-g/69137", "naam": "Fresh & easy Lunchsalade witte kaas hummus", "inhoud": "400 g", "prijs": "3.49", "omschrijving": "Lunchsalade Witte kaas hummus", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-geitenkaas-450-g/59939", "naam": "1 de Beste Maaltijdsalade geitenkaas", "inhoud": "450 g", "prijs": "4.69", "omschrijving": "Maaltijdsalade met gekookte pasta, honing-geitenkaas, een zakje walnoten en een zakje honing-tijmdressing.", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-italiaanse-kip-450-g/59944", "naam": "1 de Beste Maaltijdsalade Italiaanse kip", "inhoud": "450 g", "prijs": "4.69", "omschrijving": "Maaltijdsalade met gekookte gemarineerde pasta, gekruide gegaarde kipreepjes, pestovinaigrette, kaas en olijven", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-kip-sweet-chili-450-g/59945", "naam": "1 de Beste Maaltijdsalade kip sweet chili", "inhoud": "450 g", "prijs": "3.99", "omschrijving": "Maaltijdsalade met gekookte noedels, gegaarde kipplakjes, sweet-chili-dressing en gebakken uitjes", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-kip-450-g/59937", "naam": "1 de Beste Maaltijdsalade kip", "inhoud": "450 g", "prijs": "3.99", "omschrijving": "Maaltijdsalade met gekookte pasta, gegaarde kipplakjes en een zakje yoghurtdressing.", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-tonijn-450-g/59938", "naam": "1 de Beste Maaltijdsalade tonijn", "inhoud": "450 g", "prijs": "2.99", "omschrijving": "Maaltijdsalade met gegaarde krieltjes, gegaarde tonijn, olijfringen, gekookt ei en een een zakje vinaigrette.", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
{"url": "https://www.dekamarkt.nl/boodschappen/maaltijden-salades-tapas/maaltijdsalades/1-de-beste-maaltijdsalade-garnalen-450-g/59943", "naam": "1 de Beste Maaltijdsalade garnalen", "inhoud": "450 g", "prijs": "4.69", "omschrijving": "Maaltijdsalade met gekookte noedels, gekookte garnalen, sweet-chili-dressing en sesamzaadjes.", "aanbieding": [], "categorie": ["Maaltijden salades tapas", "Maaltijdsalades"]}
